apply plugin: 'com.huawei.ohos.hap'
apply plugin: 'com.huawei.ohos.js'

ohos {
    compileSdkVersion 5
    defaultConfig {
        compatibleSdkVersion 5
    }
    buildTypes {
        release {
            proguardOpt {
                disableProguard true
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.har'])
}
