# Project-wide Gradle settings.

# JVM Memory & Garbage Collector optimization
org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -Dfile.encoding=UTF-8

# Performance & Caching
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Android modern compilation settings
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin build optimization
kotlin.code.style=official
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
